---
title: IQB Testprofil
---

id-profile-store: `ptest`

profile-creator: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

2 profile-various:

# Testprofil - Aufgabe

id-profile: `https://raw.githubusercontent.com/iqb-vocabs/p00/master/unit.json`

| table-name-label | table-data-type | table-parameter | table-id-parameter |
| :--- | :---: | :--- | :---: |
| data-type-vocabulary Aufgabe Dialog | [data-type-vocabulary](https://w3id.org/iqb/v34/se/) | url: 'https://w3id.org/iqb/v34/se/', parameter-more-times, parameter-dialog | a11 |
| data-type-vocabulary Aufgabe Implicit | [data-type-vocabulary](https://w3id.org/iqb/v34/se/) | url: 'https://w3id.org/iqb/v34/se/', parameter-more-times, parameter-dialog | a12 |
| data-type-vocabulary Aufgabe In-form | [data-type-vocabulary](https://w3id.org/iqb/v34/se/) | url: 'https://w3id.org/iqb/v34/se/', parameter-more-times, parameter-integrated | a13 |
| Boolean Aufgabe JA/NEIN | data-type-bool | parameter-yes: ja, parameter-no: nein | a3 |
| Number Aufgabe | data-type-number | parameter-decimal: 0, parameter-min-value: 0, parameter-max-value: parameter-noone | a4 |

: {tbl-colwidths="[15,15,55,15]"}

# Testprofil - Item

id-profile: `https://raw.githubusercontent.com/iqb-vocabs/p00/master/item.json`

| table-name-label | table-data-type | table-parameter | table-id-parameter |
| :--- | :---: | :--- | :---: |
| Freitext Item A | data-type-text | parameter-textfield, parameter-language   | w2 |
| Boolean Item | data-type-bool | parameter-yes: störend, parameter-no: nicht relevant | w3 |
| Number Item | data-type-number | parameter-decimal: 0, parameter-min-value: 0, parameter-max-value: parameter-noone, parameter-seconds | w4 |
| Test data-type-vocabulary | [data-type-vocabulary](https://w3id.org/iqb/v99/v3/) | url: 'https://w3id.org/iqb/v99/v3/', parameter-more-times, parameter-deep, parameter-dialog | w5 |

: {tbl-colwidths="[15,15,55,15]"}

